steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/places-repo/api:$BUILD_ID', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/places-repo/api:latest', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'europe-west1-docker.pkg.dev/$PROJECT_ID/places-repo/api']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pt-places-api'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/places-repo/api:$BUILD_ID'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/places-repo/api:$BUILD_ID'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/places-repo/api:latest'
options:
  logging: CLOUD_LOGGING_ONLY